### ISSUE TITLE
Support setSpeed()

### ISSUE THREAD

**Issue by MPV** [minkphp/MinkSeleniumDriver#4]
Hi, 
What do you think about adding support for the Selenium setSpeed() functionality? 
Is it technically possible?

Here's the one I'm referring to:
http://release.seleniumhq.org/selenium-remote-control/0.9.0/doc/java/com/thoughtworks/selenium/DefaultSelenium.html#setSpeed(java.lang.String)

**Comment by aik099** [comment]
Closing due deprecation of the driver.
