### ISSUE TITLE
[Suggestion] Deprecate this driver

### ISSUE THREAD

**Issue by stof** [minkphp/MinkSeleniumDriver#53]
This driver relies on the deprecated Selenium protocol, through a deprecated client library: https://github.com/minkphp/Mink/issues/629#issuecomment-69176211
Thus it has some failures in the driver testsuite.

What do you think about marking this driver as deprecated entirely ? People using it should switch to Selenium2Driver. This should be easy given that the java process needed is exactly the same. What do you think @aik099 ?

**Comment by aik099** [comment]
I'm OK with that. Unless people, who use it have custom code that talks to driver internals migration to Selenium2Driver shouldn't create any issues.

**Comment by stof** [comment]
I marked the package as abandonned on Packagist: https://packagist.org/packages/behat/mink-selenium-driver

I will make a final release of this driver at the same time than the next release of other drivers even though the testsuite does not pass, to have a release compatible with recent Mink versions (people were asking for it).

The doc was already updated with a deprecation warning since https://github.com/minkphp/docs/pull/49

**Comment by stof** [comment]
the final release has been done (1.2.0)
